services:
  - type: web
    name: canai-app
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: STRIPE_SECRET
        sync: false
      - key: OPENAI_KEY
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false


